table_info = {"sample_data_sales":{
                                                                                                            "description": "The table captures detailed order line item data across various sales channels. It includes identifiers and names for sales channels, customers, products, and promotions. Additionally, it provides comprehensive date and time information for orders, including specific metrics like day of the week, month, and year. Geographic details for billing and shipping locations are also included. Financial metrics such as revenue, discounts, shipping costs, refunds, COGS (Cost of Goods Sold), and taxes are recorded. The table also tracks order and item statuses, customer types, and promotion details.",
                                                                                                            "column_description": {
                                                                                                                "sales_channel_id": "The identifier for the Sales Channel assigned by the business. This could be a code, number, or any other unique identifier used internally by the business to reference the Sales Channel. (varchar)",
                                                                                                                "sales_channel_name": "The actual name of the Sales Channel. This could be a store name, website name, or any other descriptive name for the channel through which sales are made. Possible Values: Shopify, Amazon.in, Amazon.com, Amazon.com.mx (varchar)",
                                                                                                                "sales_channel_type": "The type of Sales Channel. This field would help understand if this was a brick & mortar store, online store (D2C), marketplace, or any other channel that defines the channel type. Possible Values: D2C, Marketplace, Retail, etc.  (varchar)",
                                                                                                                "sales_channel_country": "The country where the Sales Channel is located. This could be the country of the physical store, the country where the website is hosted, or the marketplace website. Possible values: US, MX, CA, IN, etc. (varchar)",
                                                                                                                "sales_channel_state": "The state or province where the Sales Channel is located (only applicable if the sales channel is a physical store). (varchar)",
                                                                                                                "sales_channel_city": "The city where the Sales Channel is located (only applicable if the sales channel is a physical store). (varchar)",
                                                                                                                "order_key": "The key of the order. (varchar)",
                                                                                                                "order_product_key": "The key of the order product. (varchar)",
                                                                                                                "customer_key": "The key of the customer (customer id). (varchar)",
                                                                                                                "customer_type": "The type of the customer. Possible Values; New, Repeat. (varchar)",
                                                                                                                "order_date": "The date on which the order was placed. (date)",
                                                                                                                "order_time": "The timestamp at which the order was placed. (datetime)",
                                                                                                                "prior_date_day": "The date of the previous day. (date)",
                                                                                                                "next_date_day": "The date of the next day. (date)",
                                                                                                                "day_of_week": "The numeric representation of the day of the week (0-6). (int)",
                                                                                                                "day_of_week_iso": "The numeric representation of the day of the week according to the ISO standard (1-7). (int)",
                                                                                                                "day_of_week_name": "The name of the day of the week. (varchar)",
                                                                                                                "day_of_week_name_short": "The short name of the day of the week. (varchar)",
                                                                                                                "day_of_month": "The day of the month (1-31). (int)",
                                                                                                                "day_of_year": "The day of the year (1-365 or 1-366 for leap years). (int)",
                                                                                                                "week_start_date": "The start date of the week. (date)",
                                                                                                                "week_end_date": "The end date of the week. (date)",
                                                                                                                "iso_week_start_date": "The start date of the ISO week. (date)",
                                                                                                                "iso_week_end_date": "The end date of the ISO week. (date)",
                                                                                                                "iso_week_of_year": "The ISO week number of the year (1-52 or 1-53 for leap years). (int)",
                                                                                                                "month_of_year": "The month number of the year (1-12). (int)",
                                                                                                                "month_name": "The name of the month. (varchar)",
                                                                                                                "month_name_short": "The short name of the month. (varchar)",
                                                                                                                "month_start_date": "The start date of the month. (date)",
                                                                                                                "month_end_date": "The end date of the month. (date)",
                                                                                                                "quarter_of_year": "The quarter number of the year (1-4). (int)",
                                                                                                                "quarter_start_date": "The start date of the quarter. (date)",
                                                                                                                "quarter_end_date": "The end date of the quarter. (date)",
                                                                                                                "year_number": "The year number. (int)",
                                                                                                                "year_start_date": "The start date of the year. (date)",
                                                                                                                "year_end_date": "The end date of the year. (date)",
                                                                                                                "country_name": "The country name where the order was placed. (varchar)",
                                                                                                                "country_group1": "The first group to which the country belongs. (varchar)",
                                                                                                                "country_group2": "The second group to which the country belongs. (varchar)",
                                                                                                                "country_group3": "The third group to which the country belongs. (varchar)",
                                                                                                                "country_group4": "The fourth group to which the country belongs. (varchar)",
                                                                                                                "country_group5": "The fifth group to which the country belongs. (varchar)",
                                                                                                                "currency_key": "The currency code in which the payment for the order was made. (varchar)",
                                                                                                                "currency_name": "The currency name in which the payment for the order was made. (varchar)",
                                                                                                                "exchange_rate": "The exchange rate for the currency on a particular date. (float)",
                                                                                                                "product_key": "The system generated key of the product. (varchar)",
                                                                                                                "product_title": "The title of the product. (varchar)",
                                                                                                                "sku_key": "The system generated key of the SKU. (varchar)",
                                                                                                                "actual_sku": "The SKU ID as per the sales channel. (varchar)",
                                                                                                                "is_combo_sku": "Indicates whether the SKU is a combo SKU (flag). (varchar)",
                                                                                                                "final_sku": "The final SKU after mapping combo to individual SKUs. (varchar)",
                                                                                                                "brand": "The brand of the item. (varchar)",
                                                                                                                "category": "The category to which the item belongs. (varchar)",
                                                                                                                "subcategory": "The subcategory to which the item belongs. (varchar)",
                                                                                                                "product_group_l1": "The first-level product group to which the item belongs. (varchar)",
                                                                                                                "product_group_l2": "The second-level product group to which the item belongs. (varchar)",
                                                                                                                "product_group_l3": "The third-level product group to which the item belongs. (varchar)",
                                                                                                                "product_group_l4": "The fourth-level product group to which the item belongs. (varchar)",
                                                                                                                "product_group_l5": "The fifth-level product group to which the item belongs. (varchar)",
                                                                                                                "order_status": "The status of the order. (varchar)",
                                                                                                                "item_status": "The status of an item. (varchar)",
                                                                                                                "ship_city": "The city where the order was shipped to. (varchar)",
                                                                                                                "ship_state": "The state where the order was shipped to. (varchar)",
                                                                                                                "ship_country": "The country where the order was shipped to. (varchar)",
                                                                                                                "ship_postal_code": "The postal code where the order was shipped to. (varchar)",
                                                                                                                "bill_city": "The city where the order was billed at. (varchar)",
                                                                                                                "bill_state": "The state where the order was billed at. (varchar)",
                                                                                                                "bill_country": "The country where the order was billed at. (varchar)",
                                                                                                                "bill_postal_code": "The postal code where the order was billed at. (varchar)",
                                                                                                                "promotion_key": "The system generated unique key for the promotion. (varchar)",
                                                                                                                "promotion_id": "The promotion ID as per the platform. (varchar)",
                                                                                                                "promotion_name": "The name of the promotion (discount coupon name/sale name). (varchar)",
                                                                                                                "is_subscribe_and_save": "Identifies if the order is a subscribe and save order? Possible values: Yes, No (varchar)",
                                                                                                                "quantity": "The quantity of items ordered. (float)",
                                                                                                                "revenue": "The revenue of the order. (float)",
                                                                                                                "discount": "The discount applied to the order. (float)",
                                                                                                                "shipping": "The shipping charges. (float)",
                                                                                                                "refunds": "The amount refunded. (float)",
                                                                                                                "cogs": "The cost of goods sold. (float)",
                                                                                                                "taxes": "The taxes applied to the item. (float)"
                                                                                                            }
                                                                                                        },

                        "sample_data_marketing":{
                                                                                                    "description": "This table contains detailed data on marketing and advertising efforts, including identifiers and names for sales channels, customers, products, and promotions. It tracks various aspects of advertising campaigns such as ad groups, ads, and campaigns, along with their associated metrics. Comprehensive date, time, geographic, and financial information is provided, covering ad spend, impressions, clicks, conversions, and revenue. The data also includes breakdowns of product categories, reporting categories, and product groupings, offering insights into the effectiveness of promotional content and advertising strategies.",
                                                                                                    "column_description": {
                                                                                                        "f__platform": "The platform where the transaction took place. (varchar)",
                                                                                                        "f__channel": "The sales channel used for the transaction. (varchar)",
                                                                                                        "f__breakdown": "The breakdown of the transaction details. (varchar)",
                                                                                                        "country_code": "The code representing the country. (varchar)",
                                                                                                        "region": "The region where the transaction occurred. (varchar)",
                                                                                                        "date": "The date of the transaction. (date)",
                                                                                                        "refresh_ts": "The timestamp when the data was last refreshed. (timestamp)",
                                                                                                        "ad_group_id": "The unique identifier for the ad group. (varchar)",
                                                                                                        "ad_group_name": "The name of the ad group. (varchar)",
                                                                                                        "ad_id": "The unique identifier for the advertisement. (varchar)",
                                                                                                        "ad_name": "The name of the advertisement. (varchar)",
                                                                                                        "campaignid": "The unique identifier for the campaign. (varchar)",
                                                                                                        "campaignname": "The name of the campaign. (varchar)",
                                                                                                        "sku": "The stock keeping unit identifier. (varchar)",
                                                                                                        "userlist_access": "The access level of the user list. (varchar)",
                                                                                                        "product_name": "The name of the product. (varchar)",
                                                                                                        "brand": "The brand of the product. (varchar)",
                                                                                                        "reporting_category": "The category used for reporting purposes. (varchar)",
                                                                                                        "reporting_subcategory": "The subcategory used for reporting purposes. (varchar)",
                                                                                                        "internal_name": "The internal name of the product. (varchar)",
                                                                                                        "internal_sku": "The internal stock keeping unit identifier. (varchar)",
                                                                                                        "product_group_1": "The first level of product grouping. (varchar)",
                                                                                                        "product_group_2": "The second level of product grouping. (varchar)",
                                                                                                        "product_group_3": "The third level of product grouping. (varchar)",
                                                                                                        "product_group_4": "The fourth level of product grouping. (varchar)",
                                                                                                        "product_group_5": "The fifth level of product grouping. (varchar)",
                                                                                                        "spend": "The amount spent on the transaction. (float)",
                                                                                                        "impressions": "The number of impressions generated. (float)",
                                                                                                        "clicks": "The number of clicks generated. (float)",
                                                                                                        "conversions": "The number of conversions achieved. (float)",
                                                                                                        "revenue": "The revenue generated from the transaction. (float)"
                                                                                                    }

                                                                                                }

}

